version: '3.8'
services:
  backend:
    build: .
    container_name: knowledgebase-backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PORT=5432
      - POSTGRES_USER=yingcai
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=your_dbyingcaiai
      - MILVUS_HOST=127.0.0.1
      - MILVUS_PORT=19530
    depends_on: []